language: go
install: true
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
go:
  - 1.19.x
  - 1.18.x
script:
  - go mod download
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  - GOOS=windows GOARCH=amd64
  - GOOS=windows GOARCH=386
  - GOOS=linux GOARCH=amd64
  - GOOS=linux GOARCH=386
  - GOOS=linux GOARCH=arm
  - GOOS=darwin GOARCH=amd64
  - GOOS=darwin GOARCH=386
matrix:
  fast_finish: true